"""Small structural DB-API surface shared by sqlite3 and Turso drivers."""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from typing import Any, Protocol

SqlParameters = Sequence[object]
SqlRow = tuple[Any, ...]


class Cursor(Protocol):
    @property
    def description(self) -> Sequence[Sequence[object]] | None: ...

    @property
    def rowcount(self) -> int: ...

    def execute(self, sql: str, parameters: SqlParameters = ()) -> Cursor: ...

    def fetchone(self) -> SqlRow | None: ...

    def fetchall(self) -> list[SqlRow]: ...

    def fetchmany(self, size: int = 1) -> list[SqlRow]: ...

    def __iter__(self) -> Iterator[SqlRow]: ...


class Connection(Protocol):
    @property
    def in_transaction(self) -> bool: ...

    def execute(self, sql: str, parameters: SqlParameters = ()) -> Cursor: ...

    def executemany(self, sql: str, parameters: Iterable[SqlParameters]) -> Cursor: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def close(self) -> None: ...
